# Generated by Django 4.1.1 on 2022-09-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_rating',
            field=models.IntegerField(db_column='comment_rating', default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_rating',
            field=models.IntegerField(db_column='post_rating', default=0),
        ),
    ]
