# Generated by Django 4.1.1 on 2022-09-27 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_author_user_alter_author_user_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoryuser',
            old_name='cat_category',
            new_name='id_category',
        ),
        migrations.RenameField(
            model_name='categoryuser',
            old_name='category_user',
            new_name='id_user',
        ),
    ]
