# Generated by Django 4.1.1 on 2022-09-27 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_id_category_categoryuser_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_sub',
            new_name='subscribers',
        ),
    ]
